------------------------- SELECT(BASIC)----------------------------------------


-- 1. 춘 기술대학교의 학과 이름과 계열을 표시하시오.
-- 단, 출력 헤더는 "학과 명", "계열"로 표시하도록 한다
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;


--????????????????????????????????????????????
-- 2. 학과의 학과 정원을 다음과 같은 형태로 화면에 출력한다
SELECT  DEPARTMENT_NO || '의 정원은 ' || CAPACITY || '명 입니다.'
FROM TB_STUDENT
JOIN TB_DEPARTMENT td  USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO, CAPACITY
ORDER BY DEPARTMENT_NO ;


--3.
SELECT STUDENT_NAME, ABSENCE_YN, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'Y'
 AND DEPARTMENT_NAME  = '국어국문학과'
 AND SUBSTR(STUDENT_SSN, 8, 1) = '2';
 


-- 4.
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');


--5.
SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;


--6. 
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


--7. 
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8.
SELECT CLASS_NO 
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


--9.
SELECT CATEGORY 
FROM TB_DEPARTMENT
GROUP BY CATEGORY;

--10.
SELECT STUDENT_NO , STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT
WHERE ABSENCE_YN <> 'Y'
	AND STUDENT_NO LIKE '_21%'
	AND STUDENT_ADDRESS LIKE '%전주%';
	

------------------------- SELECT(FUNCTION)----------------------------------------

-- 1. 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;

--2. 
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME) <> 3;
-- 다르게 나올수있는 이유 : 컴퓨터가 멍청해서 이게 이름인지 성인지 구분 못해서


--3. 
SELECT PROFESSOR_NAME 교수이름, CEIL(MONTHS_BETWEEN(SYSDATE , TO_DATE(19 || SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD'))/12) 나이 
FROM TB_PROFESSOR;
--WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
--ORDER BY 나이;


--4. 
SELECT SUBSTR(PROFESSOR_NAME, 2, LENGTH(PROFESSOR_NAME)-1) 이름
FROM TB_PROFESSOR;



SELECT TO_DATE('2022-09-01') FROM DUAL;




--5. ?????????????????만나이 시벌탱
SELECT STUDENT_NO, STUDENT_NAME, 
CEIL((ENTRANCE_DATE - TO_DATE(19 || SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD'))/365) 입학시나이
FROM TB_STUDENT
WHERE CEIL((ENTRANCE_DATE - TO_DATE(19 || SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD'))/365) >= 20;

--6. 
SELECT TO_CHAR( TO_DATE(20221225) , 'dy') FROM DUAL;

--7
SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL; -- 2099-10-11 00:00:00.000
SELECT TO_DATE('49/10/11','YY/MM/DD') FROM DUAL; -- 2049-10-11 00:00:00.000
SELECT TO_DATE('99/10/11','RR/MM/DD') FROM DUAL; -- 1999-10-11 00:00:00.000
SELECT TO_DATE('49/10/11','RR/MM/DD') FROM DUAL; -- 2049-10-11 00:00:00.000


--8.
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';


--9
SELECT ROUND(AVG(TB_GRADE.POINT), 1) 평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NO  = 'A517178';


--10
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;




--12. ?????????????????????????????????? 년도 합치기?
SELECT DECODE(
	SUBSTR(TERM_NO, 1, 4),
	'2001' '2001', '2002', '2002', '2003', '2003', '2004', '2004', '') "년도", POINT "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4),
	'2001' '2001', '2002', '2002', '2003', '2003', '2004', '2004', '') , POINT
ORDER BY 1;


-- 13.??????????????????????????? 0인경우 표시
 SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
WHERE DECODE(ABSENCE_YN, 'Y', '1', '0')
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--14. ???????????? 셀프조인?
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
WHERE COUNT(*) >= 2
GROUP BY STUDENT_NAME, COUNT(*);


-- G1.SUBSTR(TERM_NO, 1, 4)
-- 15. ?????????????????????셀프조인?
SELECT G1.TERM_NO, G2.TERM_NO, G1.POINT
FROM TB_GRADE G1, TB_GRADE G2
JOIN TB_GRADE USING TERM_NO
ORDER BY G1.TERM_NO;